### ISSUE TITLE
some advices (8)

### ISSUE THREAD

**Issue by qjebbs** [jvantuyl/sublime_diagram_plugin#40]
Hey, this is jebbs. I modified a version of my own, which makes improvements as below. Since I am a starter in python, I won't commit my code, but hope you will adopt some of them if you think it will make the plug-in better. Thank you.

- Add setting for output file **format**, available: **png**, **svg**, **eps**, **latex**. This setting takes effect immediately.
- Add **preview** support, generating to TEMP. 

> <kbd>alt</kbd> <kbd>m</kbd> for preview, 
> <kbd>shift</kbd> <kbd>alt</kbd> <kbd>m</kbd> for final output

- In preview mode, select **multiple lines** to preview the **selected area**; select **one line** or select **none** to preview **current diagram**. (**Auto selection** of current diagram block)
- Add **diagram title** (if exists) or **number index** (if multiple diagrams file) as **suffix** to file name.
- Add <kbd>ctrl</kbd> <kbd>r</kbd> jump list support for wsd file, ensure to put "**title titletext**" in your diagram. It's useful when you have multiple diagrams in one file.
- **No more random** file name for final output files.
- **Updated** "plantuml.jar" file.
- **Brief** console messages

**Comment by jvantuyl** [comment]
Thank you for your enthusiasm.  I might be able to make more specific improvements.  In general, though, I haven't seen a lot of demand for the above features.

Most critically, this plugin isn't intended to generate final output; just a preview for use when editing.  For final output, it's best to integrate PlantUML into your build system.  That makes the differing modes, tight generation of filenames, and file-type selection unlikely to be implemented.

For the title handling, do you have code to parse these out of the file?  That would help, because I don't know how to extract them without parsing the bodies.

Could you elaborate on what "ctrl-r" jump list support is?  I'm not familiar with this.

Also, with respect to the console messages, which ones would you remove?

**Comment by qjebbs** [comment]
To be honest, I am not a programmer, I use plantuml to accelerate my activity diagram job, so maybe many of the advices is only suitable for my situation.^_^ 

about the title, I assuming the title is in one line: "title 123"...
"ctrl-r" is something like this, useful when i have multiple diagrams in one file
![qq 20160129164053](https://cloud.githubusercontent.com/assets/16953333/12671066/31e4f6ce-c6a8-11e5-80a0-3937e8fd8132.png)

I removed some of the startup check messages, so when sublime started, the console is tidy, but i keep the generating messages

**Comment by ascientist** [comment]
Could you push your features on a different repo ? I would love to have a nice output(with the same title) to embed .png in my latex file.
