### ISSUE TITLE
Package streching

### ISSUE THREAD

**Issue by TheFbomb** [jvantuyl/sublime_diagram_plugin#54]
Running on MacOSX Sierra v10.12.5, on sublime text 3 and preview as viewer, the package or node function does not display as wanted. I have no idea why actually, but on the plantuml server, the same code display as required. 
<img width="169" alt="screenshot 2017-06-27 13 55 58" src="https://user-images.githubusercontent.com/12185178/27587120-5fd75fe6-5b43-11e7-9e46-ffe7196e0db7.png">

And the one I should have:
![component1](https://user-images.githubusercontent.com/12185178/27587517-fc71217e-5b44-11e7-8a87-daded883731f.png)

**Comment by jvantuyl** [comment]
This is likely due to the PlantUML server having a different version.  I've just bumped the version for the 3.0 release, but I don't do it quite as regularly as the main PlantUML developer.

If you want to use the server, @evandrocoan has a forked version that does just that.  I believe it defaults to the public PlantUML server.

This plugin has just been resubmitted to Package Control as `diagram`.  I believe the server-based fork has been submitted to Package Control as `PlantUmlDiagrams`.  Neither seems to have been included yet, though.

I'm going to close this, as I have no ability to really impact how PlantUML renders diagrams.  I just pass it text.
